@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.legobmw99.allomancy.modules.consumables.item.consume_effects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;