@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.legobmw99.allomancy.modules.extras.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;