@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.legobmw99.allomancy.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;