@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.legobmw99.allomancy.integration.waila;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;