@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.legobmw99.allomancy.integration.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;